spring:
  datasource:
    url: jdbc:mysql://localhost/aw_ebooks?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
